// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAtVLXZDpRNp4YYQEZabOlOwfgjPN-x8Q',
    appId: '1:184530457213:android:bbcc2b74f1c0d9356c9714',
    messagingSenderId: '184530457213',
    projectId: 'singleclinic2',
    databaseURL: 'https://singleclinic2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'singleclinic2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DGwkRKcGoZbqHUvUOgJHMVj6RJ0O9fM',
    appId: '1:184530457213:ios:1586385ec79d3ac86c9714',
    messagingSenderId: '184530457213',
    projectId: 'singleclinic2',
    databaseURL: 'https://singleclinic2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'singleclinic2.appspot.com',
    iosClientId: '184530457213-87m63lqcshmeqaph8qrtjh5pq2sibrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.singleclinic',
  );
}
